name: Module Build and Publish 
run-name: "Build and Publish | Branch:${{ github.ref_name }}"
permissions: write-all   
concurrency:
  group: "${{ github.event.repository.name }}-${{ github.ref_name }}"
  cancel-in-progress: false
on:
  push:
    branches: [ "main", "dev", "uat" ]
  workflow_dispatch:
  
jobs:
  Main:
    uses: GabrielCompriLiferay/b3-exemplo-workflows/.github/workflows/ci-module.yml@main
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}
